
all:
  children:
    webservers:
      hosts:
        webserver_01:
          ansible_host: 100.26.31.150
        webserver_02:
          ansible_host: 54.226.31.215
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /Users/thilak/Downloads/MacKey_04032026.pem
